explicit:
  - name: nightly
    meta:
      branches:
        - master
        - unschedulable
    tests:
      - { regex: '^Test_(Basic|Advanced|Integration|).*$' }

scopes:
  basic:
    paths:
      - '^workflow-experiments/basic/'
    tests:
      - { regex: '^Test_Basic.*$' }

  advanced:
    paths:
      - '^workflow-experiments/advanced/'
    tests:
      - { regex: '^Test_Advanced.*$' }

  integration:
    paths:
      - '^workflow-experiments/basic/'
      - '^workflow-experiments/advanced/'
      - '^workflow-experiments/integration/'
    tests:
      - { regex: '^Test_Integration.*$' }

full:
  - '^workflow-experiments/full/'

skip:
  - '^workflow-experiments/useless/'
