apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry.fullname" . }}-config
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |
    version: 0.1
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
      cache:
        blobdescriptor: inmemory
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    {{- if .Values.auth.enabled }}
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    {{- end }}
    {{- if .Values.proxy.enabled }}
    proxy:
      remoteurl: {{ .Values.proxy.remoteUrl }}
    {{- end }}
