{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-auth
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
    {{- range .Values.auth.users }}
    {{ htpasswd .username .password }}
    {{- end }}
{{- end }}
{{- if and .Values.proxy.enabled .Values.proxy.auth.username (not .Values.proxy.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.fullname" . }}-proxy-auth
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.proxy.auth.username | quote }}
  password: {{ .Values.proxy.auth.password | quote }}
{{- end }}
