name: Execute Nightly Tests
on:
  schedule:
    - cron: '30 10 * * *'

jobs:
  get-target-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: get-branches
        id: get-branches
        run: |
          branches=$(yq -o=json '.explicit[] | select(.name == "nightly") | .meta.branches' .github/scripts/provisioning-test-scopes.yaml | jq -c '.')
          echo "branches=${branches}" >> "$GITHUB_OUTPUT"

  start-nightly-provisioning-tests:
    needs: get-target-branches
    permissions:
      actions: write
    strategy:
      matrix:
        release-branch: ${{ fromJson(needs.get-target-branches.outputs.branches) }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: invoke-nightly-test-workflow
        run: |
          gh workflow run nightly-provisioning-tests.yml --ref ${{ matrix.release-branch }}